# Generated by Django 4.1.6 on 2023-02-08 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='desempenho',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='prova',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
