# Generated by Django 4.1.6 on 2023-02-07 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0003_alter_prova_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='name',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='name',
        ),
    ]
