# Generated by Django 4.1.6 on 2023-02-08 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0003_desempenho_data_prova_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodle.professor'),
        ),
    ]
