# Generated by Django 4.1.6 on 2023-02-08 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0004_alter_questao_departamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='professor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='moodle.professor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questao',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodle.departamento'),
        ),
    ]
