# Generated by Django 4.1.6 on 2023-02-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0004_remove_aluno_name_remove_professor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadernoresposta',
            old_name='resposta_correta',
            new_name='questao',
        ),
    ]
