# Generated by Django 4.1.6 on 2023-02-07 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0005_rename_resposta_correta_cadernoresposta_questao'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcoesResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_alternativa', models.CharField(max_length=255)),
                ('alternativa', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1)),
                ('questao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodle.questao')),
            ],
        ),
    ]
