# Generated by Django 4.1.6 on 2023-02-07 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0006_opcoesresposta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opcoesresposta',
            old_name='questao_id',
            new_name='questao',
        ),
    ]
