# Generated by Django 4.1.6 on 2023-02-08 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0007_prova_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodle.professor'),
        ),
    ]
