# Generated by Django 4.1.6 on 2023-02-07 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0007_rename_questao_id_opcoesresposta_questao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpcoesResposta',
            new_name='Alternativa',
        ),
    ]
